### ISSUE TITLE
Envoy support?

### ISSUE THREAD

**Issue by mmisztal1980** [moritzheiber/consul-connect-kickstarter#1]
Hi, 
I think this example is pretty great, however it's only using the default proxy.
I was wondering if it would be possible to add envoy support to this example as well?

**Comment by moritzheiber** [comment]
@mmisztal1980 Apologies, I must've missed the notification for this issue. At the time when I was creating this kickstarter Connect didn't support using any other proxy but its own outside of Kubernetes. Do you know if these circumstance have changed?

**Comment by mmisztal1980** [comment]
not sure, but I'd assume that it should be possible to run this within a scope of a simple compose solution

**Comment by moritzheiber** [comment]
You would think so, right? Unfortunately, the documentation suggests otherwise, and the people I talked to at HashiDays last year also said it's currently not supported. I'll give it a quick glance over again ..

**Comment by moritzheiber** [comment]
According to [this](https://learn.hashicorp.com/consul/developer-segmentation/connect-envoy) it should be possible now. I'll look into it, but I don't have a lot of bandwidth right now. PRs are welcome!
